# Generated by Django 2.2.1 on 2019-05-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
