# Generated by Django 2.2.1 on 2019-05-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190528_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Author',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
