# Generated by Django 2.2.1 on 2019-05-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Content',
        ),
    ]
