# Generated by Django 2.2.1 on 2019-05-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Author',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='author name'),
        ),
    ]
