# Generated by Django 2.2.1 on 2019-05-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190528_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Author',
            field=models.CharField(blank=True, help_text='enter authorname', max_length=30, null=True, verbose_name='author name'),
        ),
    ]
